export interface SellingWindowPhase {
  phase_name: string
  target_months: number[]
  target_months_label: string
  kiosk_booking_window: string
  category: 'PUPUK_DASAR' | 'PUPUK_GENERATIF' | 'PUPUK_VEGETATIF' | 'PROTEKSI_HAMA' | 'PUPUK_BOOSTER'
  product_recommendations: string[]
  urgency: 'GOLDEN_PEAK' | 'HIGH' | 'MEDIUM'
  commercial_rationale: string
}

export interface CommercialSellingGuide {
  commodity_id: string
  crop_name: string
  golden_selling_months: number[]
  golden_months_label: string
  primary_target_input: string
  lead_time_booking: string
  kiosk_stocking_action: string
  key_production_hubs: string
  phases: SellingWindowPhase[]
}

export const COMMERCIAL_SELLING_GUIDES: Record<string, CommercialSellingGuide> = {
  COMM_01_PADI: {
    commodity_id: 'COMM_01_PADI',
    crop_name: 'Padi',
    golden_selling_months: [9, 10, 1, 2, 4, 5],
    golden_months_label: 'September – Oktober (MT 1 Rendeng) & April – Mei (MT 2 Gadu)',
    primary_target_input: 'Pupuk Dasar NPK & Urea, Herbisida Pra-Tumbuh, Pupuk Bunting Kalium Tinggi (KNO3 Putih) & Fungisida Blast',
    lead_time_booking: 'T-30 s/d T-45 hari (Sales booking kios KPL di Agustus & Maret)',
    kiosk_stocking_action: 'Kunci alokasi pupuk komersial non-subsidi di kios KPL lumbung beras nasional (Karawang, Subang, Indramayu, Sragen, Sidrap) sebelum pintu air irigasi dibuka.',
    key_production_hubs: 'Jawa Barat (Pantura), Jawa Tengah, Jawa Timur, Sulawesi Selatan',
    phases: [
      {
        phase_name: 'Olah Lahan & Pemupukan Dasar MT 1',
        target_months: [9, 10],
        target_months_label: 'September – Oktober',
        kiosk_booking_window: 'Agustus (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['NPK 15-15-15 Granular', 'Urea Granul', 'Pupuk Organik / Asam Humat', 'Herbisida Pra-Tumbuh Pretilachlor'],
        urgency: 'HIGH',
        commercial_rationale: 'Petani menyiapkan lahan serempak saat hujan pertama turun. Kios butuh pasokan NPK dan herbisida pra-tumbuh berkapasitas tonase besar.',
      },
      {
        phase_name: 'Fase Vegetatif & Pemupukan Susulan MT 1',
        target_months: [11, 12],
        target_months_label: 'November – Desember',
        kiosk_booking_window: 'Oktober (T-30)',
        category: 'PUPUK_VEGETATIF',
        product_recommendations: ['Urea Susulan', 'ZA', 'Insektisida Penggerek Batang (Klorantraniliprol / Fipronil)', 'Herbisida Selektif'],
        urgency: 'MEDIUM',
        commercial_rationale: 'Fase anakan aktif padi. Ancaman sundep dan gulma rumput teki meningkat tajam.',
      },
      {
        phase_name: 'BOOSTER GENERATIF BUNTING & PENGISIAN BULIR (GOLDEN WINDOW)',
        target_months: [1, 2],
        target_months_label: 'Januari – Februari',
        kiosk_booking_window: 'Desember (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['KNO3 Putih (Kalium Nitrat)', 'Silika Cair Soluble', 'Fungisida Blast Malai (Trisiklazol, Difenokonazol + Azoksistrobin)', 'Kalsium Foliar'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Waktu emas peningkatan bobot gabah dan pencegahan patah leher (blast). Aplikasi pupuk kalium cair dan fungisida protektif melonjak.',
      },
      {
        phase_name: 'Olah Lahan & Tanam MT 2 Gadu',
        target_months: [4, 5],
        target_months_label: 'April – Mei',
        kiosk_booking_window: 'Maret (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Benih Padi Genjah (Inpari 32/42)', 'NPK Seimbang', 'Pupuk Hayati Pengurai Jerami'],
        urgency: 'HIGH',
        commercial_rationale: 'Petani baru mencairkan kas hasil panen MT 1 dan berbelanja modal tanam tunai untuk musim gadu.',
      },
      {
        phase_name: 'Booster Generatif MT 2 Gadu',
        target_months: [7],
        target_months_label: 'Juli',
        kiosk_booking_window: 'Juni (T-30)',
        category: 'PUPUK_GENERATIF',
        product_recommendations: ['Kalium Sulfat / KNO3', 'Insektisida Wereng Coklat (Pimetrozin)', 'Silika Penguat Batang'],
        urgency: 'HIGH',
        commercial_rationale: 'Fase pengisian gabah musim kemarau dengan ancaman wereng batang coklat.',
      },
    ],
  },
  COMM_02_JAGUNG: {
    commodity_id: 'COMM_02_JAGUNG',
    crop_name: 'Jagung',
    golden_selling_months: [9, 10, 12, 2, 4, 5],
    golden_months_label: 'September – Oktober & April – Mei',
    primary_target_input: 'Benih Jagung Hibrida F1 (NK, Pioneer, Dekalb), NPK Dasar & Urea, Herbisida Selektif Atrazin, Pupuk Kalium Tongkol',
    lead_time_booking: 'T-30 hari sebelum musim hujan tiba di lahan kering',
    kiosk_stocking_action: 'Kios sentra Grobogan, Tuban, Dompu, Lampung Timur wajib buffer stock benih hibrida dan herbisida selektif jagung.',
    key_production_hubs: 'Jawa Timur (Tuban/Lamongan), Jawa Tengah (Grobogan), Lampung, NTB (Dompu/Bima)',
    phases: [
      {
        phase_name: 'Tanam & Pupuk Dasar MT 1',
        target_months: [9, 10],
        target_months_label: 'September – Oktober',
        kiosk_booking_window: 'Agustus (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Benih Hibrida F1', 'NPK Khusus Jagung', 'Urea', 'Herbisida Selektif Jagung (Atrazin + Mesotrion)'],
        urgency: 'HIGH',
        commercial_rationale: 'Puncak musim tanam jagung lahan tegalan dan tadah hujan. Permintaan benih hibrida dan herbisida pra/purna tumbuh sangat masif.',
      },
      {
        phase_name: 'Vegetatif & Proteksi Ulat Grayak FAW',
        target_months: [11],
        target_months_label: 'November',
        kiosk_booking_window: 'Oktober (T-30)',
        category: 'PUPUK_VEGETATIF',
        product_recommendations: ['Urea Susulan 1', 'Insektisida Spodoptera frugiperda / FAW (Emamektin Benzoat, Spinetoram)', 'Perekat Penembus'],
        urgency: 'HIGH',
        commercial_rationale: 'Umur 15-35 HST adalah fase kritis serangan ulat grayak jagung yang dapat menggagalkan panen.',
      },
      {
        phase_name: 'BOOSTER PENGISIAN TONGKOL & BOBOT PIPILAN (GOLDEN WINDOW)',
        target_months: [12, 2],
        target_months_label: 'Desember & Februari',
        kiosk_booking_window: 'November & Januari (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Pupuk Kalium Murni (KCl / KNO3)', 'Pupuk Daun Makro-Mikro', 'Fungisida Bulai & Hawar Daun'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase keluarnya rambut tongkol hingga pengisian biji. Petani butuh pupuk kalium untuk memaksimalkan rendemen pipilan kering 14% KA.',
      },
      {
        phase_name: 'Tanam Jagung MT 2 (Gadu)',
        target_months: [4, 5],
        target_months_label: 'April – Mei',
        kiosk_booking_window: 'Maret (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Benih Hibrida Tahan Cekaman Kering', 'NPK Granul', 'Herbisida Pembakar Gulma'],
        urgency: 'HIGH',
        commercial_rationale: 'Penanaman jagung musim gadu di lahan sawah pasca panen padi MT 1.',
      },
    ],
  },
  COMM_03_CABAI: {
    commodity_id: 'COMM_03_CABAI',
    crop_name: 'Cabai (Besar & Rawit)',
    golden_selling_months: [3, 4, 6, 9, 10, 12],
    golden_months_label: 'Juni – Juli (Booster Bunga Gadu) & Maret – April (Pupuk Dasar)',
    primary_target_input: 'Pupuk Booster Bunga (Kalsium Boron, MKP, KNO3 Putih), Pupuk Dasar Kandang Matang + NPK Seimbang, Mulsa Hitam Perak & Fungisida Antraknosa',
    lead_time_booking: 'T-45 hari (Petani cabai belanja saprodi terencana saat pemasangan bedengan & mulsa)',
    kiosk_stocking_action: 'Stok kalsium soluble dan fungisida preventif di kios sentra Kediri, Blitar, Magelang, Temanggung, Garut sebelum fase pembungaan dimulai.',
    key_production_hubs: 'Jawa Timur (Kediri/Blitar/Banyuwangi), Jawa Tengah (Magelang/Temanggung), Jawa Barat (Garut)',
    phases: [
      {
        phase_name: 'Pengolahan Lahan & Pupuk Dasar MT Gadu',
        target_months: [3, 4],
        target_months_label: 'Maret – April',
        kiosk_booking_window: 'Februari (T-45)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Dolomit / Kapur Pertanian', 'Pupuk Kandang Matang Fermentasi', 'NPK 16-16-16 Sayur', 'Karbofuran Nematisida'],
        urgency: 'HIGH',
        commercial_rationale: 'Persiapan bedengan mulsa cabai musim kemarau. Petani memborong pupuk dasar dan dolomit untuk menaikkan pH tanah.',
      },
      {
        phase_name: 'Vegetatif & Pengendalian Thrips / Kutu Daun',
        target_months: [5],
        target_months_label: 'Mei',
        kiosk_booking_window: 'April (T-30)',
        category: 'PUPUK_VEGETATIF',
        product_recommendations: ['Pupuk Daun High-N', 'Asam Amino', 'Abamektin Akarisida', 'Imidakloprid / Tiametoksam'],
        urgency: 'MEDIUM',
        commercial_rationale: 'Fase percabangan tunas air dan pembentukan tajuk tanaman.',
      },
      {
        phase_name: 'BOOSTER BUNGA & PENTIL CABAI ANTI-RONTOK (GOLDEN WINDOW)',
        target_months: [6],
        target_months_label: 'Juni',
        kiosk_booking_window: 'Mei (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Soluble Anti Busuk Pantat', 'Boron Foliar', 'MKP (Mono Kalium Fosfat 0-52-34)', 'KNO3 Putih', 'ZPT Sitokinin / Giberelin'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'WAKTU PALING KRUSIAL! Bunga pertama mekar, petani cabai rela membeli pupuk kalsium-boron dan MKP termahal demi mencegah bunga rontok.',
      },
      {
        phase_name: 'Pemeliharaan Panen Berkelanjutan & Kocor Kalium',
        target_months: [7, 8],
        target_months_label: 'Juli – Agustus',
        kiosk_booking_window: 'Juni (T-30)',
        category: 'PUPUK_GENERATIF',
        product_recommendations: ['Pupuk Kocor NPK 16-16-16 + KNO3 Putih interval 7 hari', 'Fungisida Tembaga / Difenokonazol'],
        urgency: 'HIGH',
        commercial_rationale: 'Pemetikan cabai dilakukan tiap 5-7 hari sekali hingga 15-20 petikan. Kocor kalium kontinu menjaga buah tetap padat mengkilap.',
      },
      {
        phase_name: 'BOOSTER CABAI RENDENG (MUSIM HUJAN EXTREME)',
        target_months: [12],
        target_months_label: 'Desember',
        kiosk_booking_window: 'November (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Nitrat Tinggi', 'Fungisida Sistemik Antraknosa (Azoksistrobin, Tebukonazol)', 'Silika Pengeras Dinding Sel'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Cabai musim hujan rawan busuk buah (patek). Penjualan kalsium dan fungisida antraknosa mencapai puncaknya.',
      },
    ],
  },
  COMM_04_BAWANG_MERAH: {
    commodity_id: 'COMM_04_BAWANG_MERAH',
    crop_name: 'Bawang Merah',
    golden_selling_months: [3, 5, 6, 7, 10, 11],
    golden_months_label: 'Maret (MT 1), Juni – Juli (MT 2 Gadu Raya), November (MT 3)',
    primary_target_input: 'Pupuk Pembesar Umbi (Kalium Sulfat / ZK, KNO3 Putih), NPK 16-16-16, Insektisida Ulat Grayak (Klorfenapir, Broflanilide), Fungisida Moler',
    lead_time_booking: 'T-20 hari (Siklus 55-65 hari butuh respon suplai logistik kios sangat cepat)',
    kiosk_stocking_action: 'Kios di Brebes, Nganjuk, Bima, Enrekang menyerap pupuk Kalium non-subsidi dan insektisida ulat grayak dalam volume tonase masif.',
    key_production_hubs: 'Jawa Tengah (Brebes/Demak), Jawa Timur (Nganjuk/Probolinggo), NTB (Bima)',
    phases: [
      {
        phase_name: 'Olah Lahan & Tanam MT 1',
        target_months: [1, 2],
        target_months_label: 'Januari – Februari',
        kiosk_booking_window: 'Januari (T-15)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['NPK 16-16-16', 'SP-36', 'Dolomit', 'Insektisida Ulat Daun'],
        urgency: 'HIGH',
        commercial_rationale: 'Persiapan awal tahun lahan bawang di Brebes dan sentra Nganjuk.',
      },
      {
        phase_name: 'BOOSTER UMBI BAWANG MT 1 (BULBING 35-50 HST)',
        target_months: [3],
        target_months_label: 'Maret',
        kiosk_booking_window: 'Februari (T-20)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalium Sulfat (ZK)', 'KNO3 Putih', 'Kalsium Soluble', 'Paklobutrazol Retardan'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase pembesaran umbi bawang. Pupuk kalium tinggi memperberat bobot umbi dan meningkatkan warna merah mengkilap.',
      },
      {
        phase_name: 'Olah Lahan & Tanam MT 2 (Gadu Raya Terbesar)',
        target_months: [5, 6],
        target_months_label: 'Mei – Juni',
        kiosk_booking_window: 'April (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Bibit Bawang Merah Bima/Tajuk', 'NPK Granul 16-16-16', 'Asam Humat'],
        urgency: 'HIGH',
        commercial_rationale: 'Musim tanam terluas tahunan di Brebes dan Pantura Jawa.',
      },
      {
        phase_name: 'PUNCAK EMAS NASIONAL: BOOSTER UMBI GADU (GOLDEN WINDOW)',
        target_months: [7],
        target_months_label: 'Juli',
        kiosk_booking_window: 'Juni (T-20)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalium Sulfat (ZK / SOP)', 'KNO3 Putih', 'Boron', 'Insektisida Premium Ulat Spodoptera exigua'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Bulan penjualan saprodi bawang merah terbesar di Indonesia. Ratusan miliar rupiah pupuk kalium terserap dalam 30 hari.',
      },
      {
        phase_name: 'Generatif Umbi Bawang MT 3 Off-Season',
        target_months: [11],
        target_months_label: 'November',
        kiosk_booking_window: 'Oktober (T-20)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Klorida / Nitrat', 'Kalium Tinggi', 'Fungisida Moler (Heksakonazol, Tebukonazol)'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Tanam off-season berharga jual tinggi namun resiko penyakit moler (Fusarium) tinggi.',
      },
    ],
  },
  COMM_05_KENTANG: {
    commodity_id: 'COMM_05_KENTANG',
    crop_name: 'Kentang',
    golden_selling_months: [3, 4, 6, 8, 9, 11],
    golden_months_label: 'Juni (Inisiasi Umbi Siklus 1) & November (Siklus 2)',
    primary_target_input: 'Pupuk Pembesar Umbi Padat NPK Granular (12-12-17-2), Kalium Sulfat (ZK), Fungisida Busuk Daun Phytophthora (Dimetomorf, Mankozeb, Simoksanil)',
    lead_time_booking: 'T-30 hari (Petani dataran tinggi menyukai paket pupuk + fungisida lengkap)',
    kiosk_stocking_action: 'Kios di Dieng (Wonosobo/Banjarnegara), Pangalengan, Bener Meriah mengamankan kuota fungisida sistemik dan pupuk kalium impor.',
    key_production_hubs: 'Jawa Tengah (Wonosobo/Banjarnegara), Jawa Barat (Bandung/Pangalengan), Sumatera Utara (Karo)',
    phases: [
      {
        phase_name: 'Olah Lahan & Pupuk Dasar Siklus 1',
        target_months: [3, 4],
        target_months_label: 'Maret – April',
        kiosk_booking_window: 'Februari (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Pupuk Kandang Ayam Fermentasi', 'NPK Granul 12-12-17', 'Nematisida Karbofuran'],
        urgency: 'HIGH',
        commercial_rationale: 'Awal musim tanam dataran tinggi pasca musim hujan lebat.',
      },
      {
        phase_name: 'BOOSTER INISIASI & PENGISIAN UMBI KENTANG (GOLDEN WINDOW)',
        target_months: [6],
        target_months_label: 'Juni',
        kiosk_booking_window: 'Mei (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalium Sulfat (SOP)', 'Kalsium Nitrat', 'MKP Soluble', 'Fungisida Phytophthora infestans (Dimetomorf + Mankozeb)'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase pembentukan dan pembesaran umbi kentang. Kebutuhan kalium murni dan proteksi busuk daun sangat tinggi.',
      },
      {
        phase_name: 'Olah Lahan & Pupuk Dasar Siklus 2',
        target_months: [8, 9],
        target_months_label: 'Agustus – September',
        kiosk_booking_window: 'Juli (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['NPK 12-12-17', 'Dolomit', 'Pupuk Organik Padat'],
        urgency: 'HIGH',
        commercial_rationale: 'Penanaman kentang siklus kedua sebelum musim penghujan tiba.',
      },
      {
        phase_name: 'BOOSTER GENERATIF SIKLUS 2 (PENGISIAN UMBI)',
        target_months: [11],
        target_months_label: 'November',
        kiosk_booking_window: 'Oktober (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalium Tinggi', 'Fungisida Translaminar / Sistemik Busuk Daun'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Pengisian umbi berhadapan dengan cuaca dingin basah dataran tinggi.',
      },
    ],
  },
  COMM_06_KUBIS: {
    commodity_id: 'COMM_06_KUBIS',
    crop_name: 'Kubis',
    golden_selling_months: [1, 3, 4, 6, 8, 9, 11],
    golden_months_label: 'Juni & November (Fase Pembentukan Krop Kubis)',
    primary_target_input: 'Pupuk Kalsium Boron (Cegah Krop Pecah), NPK Seimbang, Insektisida Ulat Plutella & Crocidolomia (Klorantraniliprol)',
    lead_time_booking: 'T-25 hari',
    kiosk_stocking_action: 'Penyediaan kalsium foliar dan insektisida ulat krop di Brastagi, Lembang, Kopeng, dan Wonosobo.',
    key_production_hubs: 'Jawa Barat (Bandung Barat), Jawa Tengah (Wonosobo/Magelang), Sumatera Utara (Karo)',
    phases: [
      {
        phase_name: 'Olah Lahan & Pupuk Dasar',
        target_months: [3, 4, 8, 9],
        target_months_label: 'Maret – April & Agustus – September',
        kiosk_booking_window: 'T-25 hari',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Kapur Pertanian (Dolomit)', 'Pupuk Kandang Matang', 'NPK 16-16-16'],
        urgency: 'HIGH',
        commercial_rationale: 'Persiapan bedengan dan penetralan pH tanah kubis.',
      },
      {
        phase_name: 'BOOSTER PEMBENTUKAN & PEMADATAN KROP (GOLDEN WINDOW)',
        target_months: [1, 6, 11],
        target_months_label: 'Januari, Juni, & November',
        kiosk_booking_window: 'T-25 hari',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Soluble + Boron (mencegah krop retak & busuk hitam)', 'Kalium KNO3', 'Insektisida Ulat Daun'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Daun mulai melipat membentuk krop padat. Kalsium mutlak dibutuhkan untuk daya simpan dan berat krop.',
      },
    ],
  },
  COMM_07_TOMAT: {
    commodity_id: 'COMM_07_TOMAT',
    crop_name: 'Tomat',
    golden_selling_months: [2, 3, 5, 7, 8, 10],
    golden_months_label: 'Mei & Oktober (Fase Pembungaan & Pentil Buah Tomat)',
    primary_target_input: 'Pupuk Kalsium Anti Blossom-End-Rot (BER), Booster Bunga MKP, Insektisida Penggorok Daun (Liriomyza)',
    lead_time_booking: 'T-30 hari',
    kiosk_stocking_action: 'Suplai pupuk kalsium cair chelate dan fungisida tembaga di Garut, Bandung Barat, Malang, Kerinci.',
    key_production_hubs: 'Jawa Barat (Garut/Bandung Barat), Jawa Timur (Malang), Sumatera Barat (Agam/Tanah Datar)',
    phases: [
      {
        phase_name: 'Olah Lahan & Pupuk Dasar',
        target_months: [2, 3, 7, 8],
        target_months_label: 'Februari – Maret & Juli – Agustus',
        kiosk_booking_window: 'T-30 hari',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Dolomit Dosis Tinggi', 'NPK Seimbang 16-16-16', 'Pupuk Organik'],
        urgency: 'HIGH',
        commercial_rationale: 'Pengapuran tanah krusial untuk mencegah kekurangan kalsium sejak bibit ditanam.',
      },
      {
        phase_name: 'BOOSTER BUNGA & BUAH MUDA ANTI-BUSUK PANTAT (GOLDEN WINDOW)',
        target_months: [5, 10],
        target_months_label: 'Mei & Oktober',
        kiosk_booking_window: 'April & September (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Chelate / Nitrat Kalsium (anti-pantat gosong)', 'MKP (0-52-34)', 'Boron Foliar', 'ZPT Sitokinin'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase pembungaan dan pentil tomat. Tanpa kalsium boron, 30-40% buah tomat akan mengalami busuk pantat (BER).',
      },
    ],
  },
  COMM_08_SEMANGKA: {
    commodity_id: 'COMM_08_SEMANGKA',
    crop_name: 'Semangka',
    golden_selling_months: [2, 3, 5, 7, 8, 10],
    golden_months_label: 'Mei & Oktober (Fase Polinasi & Pembesaran Buah Brix Tinggi)',
    primary_target_input: 'Pupuk Kalium Murni (Kalium Nitrat & Kalium Sulfat), Kalsium Boron, Pupuk Dasar Organik, Insektisida Kutu Kebul',
    lead_time_booking: 'T-30 hari',
    kiosk_stocking_action: 'Pemasaran gencar paket pemanis semangka (Brix Booster) di Banyuwangi, Tuban, Lampung Selatan, Grobogan.',
    key_production_hubs: 'Jawa Timur (Banyuwangi/Tuban), Lampung (Lampung Selatan), Jawa Tengah (Demak/Grobogan)',
    phases: [
      {
        phase_name: 'Olah Lahan & Pupuk Dasar',
        target_months: [2, 3, 7, 8],
        target_months_label: 'Februari – Maret & Juli – Agustus',
        kiosk_booking_window: 'T-30 hari',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Pupuk Kandang Matang Fermentasi', 'NPK 15-15-15', 'SP-36', 'Karbofuran'],
        urgency: 'HIGH',
        commercial_rationale: 'Persiapan bedengan pasir/alluvial sentra semangka pesisir.',
      },
      {
        phase_name: 'BOOSTER POLINASI, UKURAN BUAH & BRIX MANIS (GOLDEN WINDOW)',
        target_months: [5, 10],
        target_months_label: 'Mei & Oktober',
        kiosk_booking_window: 'April & September (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Boron Soluble (anti hollow-heart / rongga kosong)', 'Kalium Sulfat (ZK) Pemacu Gula & Warna Merah', 'KNO3 Putih'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase penyerbukan dan pembesaran buah (umur 35-55 HST). Kalium tinggi mendongkrak kemanisan brix > 11%.',
      },
    ],
  },
  COMM_09_MELON: {
    commodity_id: 'COMM_09_MELON',
    crop_name: 'Melon',
    golden_selling_months: [2, 3, 5, 7, 8, 10],
    golden_months_label: 'Mei & Oktober (Fase Pembentukan Jaring Netting & Pemanisan Brix)',
    primary_target_input: 'Pupuk Kalsium Boron Soluble, Kalium Sulfat (ZK), Pupuk Fertigasi Soluble Grade, Fungisida Embun Tepung',
    lead_time_booking: 'T-30 hari',
    kiosk_stocking_action: 'Edukasi aplikasi kalsium presisi agar jaring melon rapat sempurna tanpa retak fatal di sentra Ngawi, Madiun, Boyolali.',
    key_production_hubs: 'Jawa Timur (Ngawi/Madiun/Banyuwangi), Jawa Tengah (Boyolali/Klaten), DIY (Kulon Progo)',
    phases: [
      {
        phase_name: 'Olah Lahan & Pupuk Dasar',
        target_months: [2, 3, 7, 8],
        target_months_label: 'Februari – Maret & Juli – Agustus',
        kiosk_booking_window: 'T-30 hari',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Dolomit', 'Pupuk Dasar NPK Makro', 'Trichoderma'],
        urgency: 'HIGH',
        commercial_rationale: 'Sanitasi lahan dan penyiapan sistem irigasi tetes / mulsa.',
      },
      {
        phase_name: 'BOOSTER NETTING & PEMANISAN BRIX (GOLDEN WINDOW)',
        target_months: [5, 10],
        target_months_label: 'Mei & Oktober',
        kiosk_booking_window: 'April & September (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Kalsium Soluble Murni (fase jaring umur 35-45 HST)', 'Kalium Bebas Klorin Dosis Tinggi (umur 50-65 HST pemacu brix 13-15%)', 'Fungisida Powdery Mildew'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase netting menentukan kelas ekspor/supermarket. Kalsium mencegah retak buah dan kalium memaksimalkan aroma & brix.',
      },
    ],
  },
  COMM_10_KELAPA_SAWIT: {
    commodity_id: 'COMM_10_KELAPA_SAWIT',
    crop_name: 'Kelapa Sawit',
    golden_selling_months: [2, 3, 4, 8, 9, 10],
    golden_months_label: 'Maret – April (Semester 1) & September – Oktober (Semester 2 / High Crop)',
    primary_target_input: 'Pupuk Tunggal Makro (MOP / KCl 60% K2O, Urea 46% N, Rock Phosphate 28% P2O5, Kieserite 27% MgO) & Pupuk Mikro Borate',
    lead_time_booking: 'T-60 s/d T-90 hari (Pengadaan tender perkebunan korporasi & KUD plasma butuh PO 2-3 bulan sebelumnya)',
    kiosk_stocking_action: 'Gudang distributor di Riau, Sumut, Jambi, Sumsel, dan Kalteng harus ready stock ribuan ton MOP dan Kieserite sebelum musim aplikasi.',
    key_production_hubs: 'Riau, Sumatera Utara, Sumatera Selatan, Kalimantan Barat, Kalimantan Tengah',
    phases: [
      {
        phase_name: 'PEMUPUKAN SEMESTER 1 (AWAL TAHUN)',
        target_months: [3, 4],
        target_months_label: 'Maret – April',
        kiosk_booking_window: 'Januari – Februari (T-60)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Urea (46% N) pemacu pelepah baru', 'Rock Phosphate (RP) perakaran', 'Kieserite (MgO) klorofil daun'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Aplikasi pupuk semester pertama untuk pemulihan tanaman setelah masa Low Crop.',
      },
      {
        phase_name: 'Pemeliharaan Piringan & Proteksi Hama',
        target_months: [5, 6],
        target_months_label: 'Mei – Juni',
        kiosk_booking_window: 'April (T-30)',
        category: 'PROTEKSI_HAMA',
        product_recommendations: ['Herbisida Glifosat / Glufosinat Amonium', 'Insektisida Ulat Api / Ulat Kantung'],
        urgency: 'MEDIUM',
        commercial_rationale: 'Pembersihan gawangan dan piringan sawit agar memudahkan pemungutan brondolan saat panen.',
      },
      {
        phase_name: 'PUNCAK EMAS: PEMUPUKAN SEMESTER 2 SAAT HIGH CROP (GOLDEN WINDOW)',
        target_months: [9, 10],
        target_months_label: 'September – Oktober',
        kiosk_booking_window: 'Juli – Agustus (T-60)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['MOP / KCl (Muriate of Potash 60% K2O)', 'Urea', 'Borate (pupuk mikro boron perkebunan)'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'PUNCAK PENYERAPAN PUPUK PERKEBUNAN TERBESAR! Kalium (MOP) menentukan pembentukan minyak CPO dan berat janjang TBS.',
      },
    ],
  },
  COMM_11_ALPUKAT: {
    commodity_id: 'COMM_11_ALPUKAT',
    crop_name: 'Alpukat',
    golden_selling_months: [3, 4, 6, 7, 8, 9],
    golden_months_label: 'Juni – Juli (Booster Bunga & Pentil Buah) & Maret – April (Pemulihan Pohon & Pupuk Dasar)',
    primary_target_input: 'Pupuk Booster Bunga (Kalsium, Boron, MKP, KNO3 Putih, Asam Amino), Pupuk Organik Fermentasi + NPK Seimbang, Kalium Sulfat (SOP), Insektisida Lalat Buah',
    lead_time_booking: 'T-30 s/d T-45 hari (Sales booking kios di Mei menyambut musim bunga Juli)',
    kiosk_stocking_action: 'Kios di Malang (Wajak/Dampit), Blitar, Pasuruan, Semarang (Bandungan), Lampung Timur harus distock paket kalsium boron dan kalium pembesar buah.',
    key_production_hubs: 'Jawa Timur (Malang/Pasuruan/Blitar), Jawa Tengah (Semarang/Boyolali), Lampung (Lampung Timur), Jawa Barat (Sukabumi/Garut)',
    phases: [
      {
        phase_name: 'Pemulihan Pasca Panen & Pupuk Dasar Pohon',
        target_months: [3, 4],
        target_months_label: 'Maret – April',
        kiosk_booking_window: 'Februari (T-45)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Pupuk Kandang Kambing Fermentasi (20-30 kg/pohon)', 'Dolomit (Penetral pH tanah piringan ke 6.0-6.8)', 'NPK 16-16-16 Seimbang (500-1000 gr/pohon)', 'Asam Humat Pengurai Akar'],
        urgency: 'HIGH',
        commercial_rationale: 'Pohon alpukat baru selesai panen besar di Nov-Feb. Tanaman mengalami kelelahan nutrisi dan butuh pupuk dasar organik + NPK seimbang untuk pemulihan dan flush tunas baru.',
      },
      {
        phase_name: 'Pertumbuhan Vegetatif & Daun Muda (Flush)',
        target_months: [5, 6],
        target_months_label: 'Mei – Juni',
        kiosk_booking_window: 'April (T-30)',
        category: 'PUPUK_VEGETATIF',
        product_recommendations: ['Pupuk Daun Nitrogen Seimbang & Asam Amino', 'Insektisida Ulat Kipat (Cricula trifenestrata) pemakan daun muda', 'Fungisida Tembaga Antraknosa Daun'],
        urgency: 'MEDIUM',
        commercial_rationale: 'Fase pendewasaan daun menjelang masa stres air (dry spell) yang memicu inisiasi mata tunas bunga.',
      },
      {
        phase_name: 'WAKTU EMAS: BOOSTER INISIASI BUNGA & PENTIL BUAH (GOLDEN WINDOW)',
        target_months: [6, 7, 8],
        target_months_label: 'Juni – Juli (Bunga Mekar) s.d. Agustus (Pentil Buah)',
        kiosk_booking_window: 'Mei – Juni (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: [
          'Kalsium Boron Soluble (mencegah rontok bunga & pentil)',
          'MKP (Mono Kalium Fosfat 0-52-34) perangsang bunga serempak',
          'KNO3 Putih (Kalium Nitrat) penguat tangkai bunga',
          'Asam Amino & ZPT Sitokinin pemacu pembelahan sel pentil',
          'Paclobutrazol (khusus kebun komersial induksi off-season)',
        ],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'WAKTU EMAS PENJUALAN PUPUK ALPUKAT! Jika petani tidak memberikan Kalsium, Boron, dan Kalium saat bunga mekar, hingga 95% bunga dan pentil alpukat bisa rontok massal. Di periode ini petani sangat loyal membeli pupuk booster berkualitas tinggi.',
      },
      {
        phase_name: 'Pembesaran Buah, Daging Tebal & Kualitas Lemak (Fruit Sizing)',
        target_months: [8, 9, 10],
        target_months_label: 'Agustus – September – Oktober',
        kiosk_booking_window: 'Juli (T-30)',
        category: 'PUPUK_GENERATIF',
        product_recommendations: [
          'Kalium Sulfat (SOP / ZK) bebas klorin untuk akumulasi minyak nabati dan tekstur pulen mentega',
          'Kalsium Foliar (mencegah kulit pecah & busuk ujung buah)',
          'Insektisida Atraktan Lalat Buah (Methyl Eugenol & Spinosad)',
          'Fungisida Kanker Batang (Phytophthora cinnamomi)',
        ],
        urgency: 'HIGH',
        commercial_rationale: 'Fase pengisian bobot buah dari ukuran bola pingpong menuju ukuran panen (400-800 gr/buah). Kalium sulfat mendongkrak grade buah ke kelas premium supermarket.',
      },
    ],
  },
  COMM_12_TEMBAKAU: {
    commodity_id: 'COMM_12_TEMBAKAU',
    crop_name: 'Tembakau',
    golden_selling_months: [3, 4, 5, 6, 7],
    golden_months_label: 'Mei – Juni (Pupuk Daun & Kalium Bebas Klorin)',
    primary_target_input: 'Pupuk Non-Klorin Bebas Cl- (KNO3 Putih, ZK / Kalium Sulfat, NPK Tembakau Khusus), Insektisida Ulat Grayak & Kutu Tembakau',
    lead_time_booking: 'T-30 hari (Petani tembakau sangat patuh instruksi pabrik rokok perihal larangan klorin)',
    kiosk_stocking_action: 'Edukasi kios di Temanggung, Jember, Pamekasan, Lombok Timur: JANGAN JUAL pupuk berklorin (KCl/MOP). Pastikan stok KNO3 dan ZK melimpah.',
    key_production_hubs: 'Jawa Timur (Jember/Pamekasan/Bojonegoro), Jawa Tengah (Temanggung/Kendal), NTB (Lombok Timur)',
    phases: [
      {
        phase_name: 'Persemaian & Sanitasi Lahan',
        target_months: [3, 4],
        target_months_label: 'Maret – April',
        kiosk_booking_window: 'Februari (T-30)',
        category: 'PUPUK_DASAR',
        product_recommendations: ['Fungisida Rebah Semai (Propamokarb)', 'Pupuk Organik Bebas Klorin', 'NPK Nitrat Khusus'],
        urgency: 'HIGH',
        commercial_rationale: 'Persiapan bibit rumah naungan dan olah lahan guludan.',
      },
      {
        phase_name: 'PUNCAK EMAS: VEGETATIF DAUN & KALIUM NON-KLORIN (GOLDEN WINDOW)',
        target_months: [5, 6, 7],
        target_months_label: 'Mei – Juli',
        kiosk_booking_window: 'April (T-30)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['KNO3 Putih murni', 'ZK (Kalium Sulfat bebas klorin)', 'Asam Amino Foliar', 'Insektisida Klorfenapir + Emamektin'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Daun tembakau adalah komoditas bernilai tinggi. Klorin dilarang keras karena merusak daya bakar rokok. Penjualan pupuk KNO3 dan ZK melonjak tinggi.',
      },
    ],
  },
  COMM_13_ANGGREK: {
    commodity_id: 'COMM_13_ANGGREK',
    crop_name: 'Anggrek',
    golden_selling_months: [5, 6, 10, 11],
    golden_months_label: 'Juni – Juli & Oktober – November (Fase Spike Induction / Induksi Bunga)',
    primary_target_input: 'Pupuk Foliar Khusus Anggrek High P-K (10-52-10 atau MKP 0-52-34), Vitamin B1 Anti-Stres, Kalsium Soluble, Bakterisida Busuk Lunak',
    lead_time_booking: 'T-15 hari (Nursery komersial membeli pupuk foliar secara rutin)',
    kiosk_stocking_action: 'Display pupuk anggrek di sentra tanaman hias Rawa Belong (Jakarta), BSD Tangsel, Batu Malang, dan Lembang.',
    key_production_hubs: 'Banten (Tangerang Selatan), DKI Jakarta (Rawa Belong), Jawa Timur (Batu/Malang), Jawa Barat (Lembang)',
    phases: [
      {
        phase_name: 'Pemeliharaan Vegetatif & Anakan Baru',
        target_months: [3, 4, 8, 9],
        target_months_label: 'Maret – April & Agustus – September',
        kiosk_booking_window: 'T-15 hari',
        category: 'PUPUK_VEGETATIF',
        product_recommendations: ['Pupuk Foliar High N (30-10-10)', 'Vitamin B1 Cair', 'Fungisida Kontak'],
        urgency: 'MEDIUM',
        commercial_rationale: 'Pertumbuhan tunas keiki dan batang semu baru.',
      },
      {
        phase_name: 'WAKTU EMAS INDUKSI TANGKAI BUNGA / SPIKE INDUCTION (GOLDEN WINDOW)',
        target_months: [5, 6, 10, 11],
        target_months_label: 'Juni – Juli & Oktober – November',
        kiosk_booking_window: 'Mei & September (T-20)',
        category: 'PUPUK_BOOSTER',
        product_recommendations: ['Pupuk Foliar High P-K (10-52-10 / 0-52-34)', 'Kalsium Organik pembesar kuntum', 'ZPT Sitokinin pemacu spike', 'Bakterisida Agrimycin'],
        urgency: 'GOLDEN_PEAK',
        commercial_rationale: 'Fase merangsang keluarnya spike tangkai bunga agar bunga mekar serempak menyambut musim panen Natal/Tahun Baru dan hajatan pertengahan tahun.',
      },
    ],
  },
}

export function getCommercialSellingGuide(commodityId: string): CommercialSellingGuide | undefined {
  return COMMERCIAL_SELLING_GUIDES[commodityId]
}

export function getMonthlyActiveSellingOpportunities(month: number): Array<{
  cropId: string
  cropName: string
  phase: SellingWindowPhase
  isGoldenPeak: boolean
}> {
  const result: Array<{
    cropId: string
    cropName: string
    phase: SellingWindowPhase
    isGoldenPeak: boolean
  }> = []

  Object.values(COMMERCIAL_SELLING_GUIDES).forEach((guide) => {
    guide.phases.forEach((phase) => {
      if (phase.target_months.includes(month)) {
        result.push({
          cropId: guide.commodity_id,
          cropName: guide.crop_name,
          phase,
          isGoldenPeak: phase.urgency === 'GOLDEN_PEAK',
        })
      }
    })
  })

  // Sort: GOLDEN_PEAK first
  return result.sort((a, b) => (b.isGoldenPeak ? 1 : 0) - (a.isGoldenPeak ? 1 : 0))
}
